# Generated by Django 4.2.1 on 2023-05-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_height_feet_alter_player_height_inches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
